### ISSUE TITLE
Petitlyrics is not supported anymore? 

### ISSUE THREAD

**Issue by nanoha25** [franklai/lyric-get#6]
Recently I use the Lyric Get and realize Petitlyrics site is not within the support list. Is it possible to restore the support or impossible from now then? 

Also, the old http://franklai-lyric-get.appspot.com/ site no longer works. Any site link will only return an "Error". I am currently using the one hosted on Azure.

**Comment by franklai** [comment]
Petitlyrics is dropped due to Google App Engine blocking and non Japanese IP blocking.
I can try if sending request from Azure will work or not.

Some sites on http://franklai-lyric-get.appspot.com/ are broken now, but most sites work. For example uta-net, utamap still work.

**Comment by franklai** [comment]
Petitlyrics is not able to support on GAE due to http header will be changed to all lower case.

Instead of GAE, azure version has petitlyrics implementation. Please try https://lyric-get-node-test1.azurewebsites.net/
