### ISSUE TITLE
fix for petitlyrics???

### ISSUE THREAD

**Issue by bbyboo** [franklai/lyric-get#8]
is there ANY WAY that you can fix petitlyrics? some of the lyrics i'm looking for are _ONLY_ on petitlyrics, but I CAN'T use the app to pull them down in plain text format

moreover, they've also integrated their lyrics as an img/png for some reason now??? and ocr/ online character recognition will NOT recognize the japanese & english characters properly, so I'd really like to have a fix for petitlyrics since its got a lot of rare japanese lyrics that i'm looking for & can't find anywhere else. any help is appreciated, or an alternative way to be able to access them......

**Comment by franklai** [comment]
You can use http://lyric-get-node-test1.azurewebsites.net/ which is on Azure and support petitlyrics.
