### ISSUE TITLE
Adding Hoick.jp

### ISSUE THREAD

**Issue by dragonzeron** [franklai/lyric-get#9]
I was wondering if you could add Hoick.jp as its officially licensed by JASRAC and has the anti Lyric copy so I was wondering if you could update it

**Comment by franklai** [comment]
Thanks for the information.

Hoick.jp is added to https://lyric-get-node-test1.azurewebsites.net/ and python version will ask azure for the result (442ebb83577bd19fec7c8496d940c611f64af49a)

**Comment by dragonzeron** [comment]
is there a chance you can put it on the other site as well or is the HTTPS thing diffrent

**Comment by franklai** [comment]
https://franklai-lyric-get.appspot.com/ is also supported, through asking azure.
